pipeline {
   agent any

   tools {
      // Install the Maven version configured as "M3" and add it to the path.
   }

   stages {
      stage('Build') {
         steps {
            // Get the repository from GitHub
            git 'https://github.com/cwiechmann/sample-api-project.git'

            // Run Maven 
            sh "apim.sh api import -c ./config.json"
         }
      }
   }
}
